[package]
name = "shellenv"
version = "0.1.0"
authors = ["Nick Murphy <comfortablynick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.1"
serde = { version = "1.0.98", features = ["derive"] }
