[package]
name = "shellenv"
version = "0.1.0"
authors = ["Nick Murphy <comfortablynick@gmail.com>"]
description = "Parses toml file of configuration into shell environment files"
edition = "2018"

[dependencies]
toml = "0.5.1"
serde = { version = "1.0.98", features = ["derive"] }
# clap = { version = "3.0.0-beta.1", git = "https://github.com/clap-rs/clap.git", branch = "v3-master" }
clap = "3.0.0-beta.1"
env_logger = "0.7"
log = "0.4.8"
anyhow = "1.0"
chrono = "0.4"
